### PR TITLE
fixed text issues

### PR DESCRIPTION
**Pull request by miragzamov**
Fixed text errors in strings.xml not all !

### CODE REVIEW

**Comment by Jetrom17** [comment]
These changes are approved. ✅

**Review by Jetrom17 — APPROVED** [review]
Grammar corrected. ✅

**Comment by HanzoDev1375** [comment]
@miragzamov Thank you for your participation. Can you add Arabic translation?

**Comment by HanzoDev1375** [comment]
@Jetrom17 I also added several new translations, update them according to your country

**Comment by miragzamov** [comment]
@miragzamov no i don't know arabic

**Comment by miragzamov** [comment]
@HanzoDev1375 no I don't know arabic

**Comment by miragzamov** [comment]
.

**Comment by HanzoDev1375** [comment]
> @HanzoDev1375 no I don't know arabic

@miragzamov No problem. Thank you for your participation. I will do it in the next few days. Do not close this PR

**Pull request merged**
