### PR TITLE
Language and workflow configured.

### PR DESCRIPTION
**Pull request by Jetrom17**
Every build is now executed by the `Android.yml` manifest, which generates a debug-type APK for users to test. This can be accessed in the "Actions" section. Download the appropriate architecture and unzip the APK for download.

The language has been configured correctly following the pattern from the string "values-fa" to "values-pt-rBR." This is displayed when accessing the settings, as that is where the strings are configured.

Screenshot_20241007-094842

The following needs to be done:

- [x] Configuration of strings throughout the entire application, not just in the "settings" section of the app.

### CODE REVIEW

**Comment by HanzoDev1375** [comment]
@Jetrom17 Please update your repository because I added several new translations, update them too, then create a PR or update the same PR. Thanks

**Comment by Jetrom17** [comment]
@HanzoDev1375 done.

> Updating the code due to branch conflicts.

**Comment by HanzoDev1375** [comment]
@Jetrom17 Did you add new Portuguese translations?

**Comment by Jetrom17** [comment]
> @Jetrom17 Did you add new Portuguese translations?

No. I deleted my changes so as not to conflict with yours.

**Comment by HanzoDev1375** [comment]
> > @Jetrom17 Did you add new Portuguese translations?
> 
> No. I deleted my changes so as not to conflict with yours.

Well apply your changes now

**Comment by Jetrom17** [comment]
@HanzoDev1375 Also create a website using your markdown.

https://github.com/Jetrom17/GhostIDE-Web

[Github]

https://github.com/Jetrom17/GhostIDE-Web

[Website]

**Comment by Jetrom17** [comment]
> Well apply your changes now

I already did. Only you see the changes made and the commit.

**Comment by HanzoDev1375** [comment]
I will fix it later, don't worry

**Comment by Jetrom17** [comment]
> I will fix it later, don't worry

Solve what? Just accept the pull request.

**Pull request merged**
